version: "3.8"
services:
  catalog-service:
    depends_on:
      polar_postgres:
        condition: service_started
      config-service:
        condition: service_healthy
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar_postgres:5432/polardb-catalog
      - SPRING_PROFILES_ACTIVE=testdata
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_CLOUD_CONFIG_FAIL_FAST=true
      - SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS=20


  polar_postgres:
    image: postgres:14.4
    container_name: "polar_postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=polardb-catalog


  config-service:
    image: "config-service"
    container_name: "config-service"
    ports:
      - 8888:8888
    healthcheck:
      # -f makes curl fail if the HTTP status is 4xx or 5xx
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s   # Give it some breathing room
      timeout: 5s
      retries: 10     # Total wait time: ~100 seconds
      start_period: 30s # Docker won't count failures for the first 30s
